### ISSUE TITLE
Using a token to create a client..?

### ISSUE THREAD

**Issue by tyddynonn** [mlowijs/tesla_api#16]
Great module! Just what I'm looking for. 

Works fine when I specify username & password, but when I tried to use a pre-existing token to create a client..

-------------------------------------------
user=None
pw=None
tk='token string here'
client=TeslaApiClient(email=user, password=pw, token=tk)
-----------------------------------------------------------

Throws 'TypeError: __init__() got an unexpected keyword argument 'token'

The source here suggests that this should work, and I've installed the latest version (pip install tesla-api). Python 3.5

Any ideas?

**Comment by mlowijs** [comment]
Hi! I didn't release a new version yet to PyPI, let me do that right now.

**Comment by mlowijs** [comment]
I just released version 2.0.0 to PyPI, which should be available soon. Let me know if you still have problems after updating!

**Comment by tyddynonn** [comment]
Thanks for the speedy response, and pip now shows tesla-api at version 2.0.0

The TypeError is fixed; but there's a new issue:

If I do:

client = TeslaApiClient(email=user,password=pw, token=None)
vehicles = client.list_vehicles()
for v in vehicles:
    print(v.vin)

I get 

TypeError: 'coroutine' object is not iterable
sys:1: RuntimeWarning: coroutine 'TeslaApiClient.list_vehicles' was never awaited
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x76aa39b0>

Same if I use the token rather than the username & pw

Not sure what to do about this. Apologies - I'm more of a C#/Javascript man!

**Comment by tyddynonn** [comment]
Thanks for the speedy response - all downloaded OK. 

Just need to upgrade to Python 3.8 now to get asyncio.run working ;-)

**Comment by tyddynonn** [comment]
So Python 3.8 installed & working, now I get a different error

  File "/usr/local/lib/python3.8/site-packages/tesla_api/__init__.py", line 67, in authenticate
    expiry_time = timedelta(seconds=self.token['expires_in'])
TypeError: string indices must be integers

I'm afraid I'm not up to speed with python debugging so I'm not sure how to drop into the relevant bit of the tesla-api code to see what is going on. Maybe self.token is getting created as an Array rather than a Dict?

**Comment by mlowijs** [comment]
Hi there! I think we made a little oversight here. The `token` parameter should be set to a Token dict, looking like:
```python
{
  "access_token": "AN_ACCESS_TOKEN",
  "refresh_token": "A_REFRESH_TOKEN",
  "expires_in": 123567,
  "created_at": "2020-01-01T00:00:00"
}
```

You could probably make it work for once by setting the `token` parameter to:

```python
{
  "access_token": "",
  "refresh_token": "A_VALID_REFRESH_TOKEN_HERE",
  "expires_in": 0,
  "created_at": "2020-01-01T00:00:00"
}
```

Or use your username and password one time and then grab the `token` property from the `TeslaApiClient`!

**Comment by tyddynonn** [comment]
Thanks again, I can work with this. Just need the token to be publicly accessible from the client - at the moment it always returns null. As you can probably tell, I'm new to Python - more a C# & Javascript person..

**Comment by mlowijs** [comment]
Hey, I'm more of a C# person myself, so I understand you 😉. The `token` property should be publically accessible from the client:

```python
async def main():
  client = TeslaApiClient("your@email.com", "your@password.com")
  await client.list_vehicles()
  print(clienttoken)
```

**Comment by tyddynonn** [comment]
Thanks Michael - I tried using client.token and got null. Should it be client[‘token’] or clienttoken without the dot?

Thanks

Chris

**Comment by Dreamsorcerer** [comment]
I plan to add some features around this, and some documentation to show how to use this properly.

But, as demonstrated above, you need to use the client first (e.g. client.list_vehicles()) before the token is retrieved and saved to that attribute.
After that you should be able to access client.token and get a dict object.

To save/restore with the token, I've been using `json.dump()` to store the token, and then loading it back with `json.load()` to be passed into a file.

A fuller example would therefore be something like:

```
async def main():
  email = password = token = None
  try:
    token = json.load(open("token_file"))
  except OSError:
    email = input()
    password = input()
  client = TeslaApiClient(email, password, token)
  await client.list_vehicles()

  # If successful, save token.
  json.dump(client.token, open("token_file", "w"))
```

**Comment by tyddynonn** [comment]
Perfect, many thanks for your help. I hadn’t appreciated that I had to ‘use’ the client to get the token property populated. But looking at your code again, it’s obvious. Doh!

 

I’ll try to get on with it on my own now 😊

**Comment by mlowijs** [comment]
@Dreamsorcerer We should probably make it so that you can pass in a refresh token and let the client request a fresh token for us, what do you think??

**Comment by tyddynonn** [comment]
That’s a good idea - but I also like the auto-refresh that it does now. 

Perhaps when you pass in a token dict, which of course includes the refresh token, check if close to refresh time and do it automatically?

Best

Chris

**Comment by mlowijs** [comment]
@tyddynonn The client already does that; it checks whether your access token has expired and will request a new one based on the refresh token. I'm proposing to let you pass just the refresh token into the `TeslaApiClient`, instead of the full dictionary. Or perhaps we should support both a refresh token _or_ the full dict.

**Comment by Dreamsorcerer** [comment]
I'm not sure I see the use case..
If you want to restore from a token, it's more efficient to use the full token which appears to be valid for 45 days. In what case would you only want to save the refresh token?

I'm currently waiting for my token to expire so I can test out the refresh stuff. I find it rather odd that you would be able to fetch a new API token, after it had expired (at which point you are no longer authenticated to use the service).

**Comment by tyddynonn** [comment]
I'm easy with just using the full dict. The main reason is to avoid embedding username/pw details anywhere...

**Comment by Dreamsorcerer** [comment]
@tyddynonn The next release will have some changes to this. It handles the JSON, so you should now just pass in the string format. There is also a callback you should pass into the constructor to save the token. So, that previous example will now look more like this:
```
def save_token(token):
    open("token_file", "w").write(token)

async def main():
  email = password = token = None
  try:
    token = open("token_file").read()
  except OSError:
    email = input()
    password = input()
  client = TeslaApiClient(email, password, token, on_new_token=save_token)
```

The callback means you don't need to worry about when the token is available. But, more importantly, it will allow you to automatically save any new tokens (from a refresh), so you don't end up with an invalid/expired token.

**Comment by Dreamsorcerer** [comment]
README has been updated with the current best practices on master (will need a new release for pip).
