### ISSUE TITLE
Unable to set vehicle charge limit

### ISSUE THREAD

**Issue by pascal876** [mlowijs/tesla_api#17]
Many thanks for your work with this project
I have an issue with using set_charge_limit(percentage) in class Charge:

Whenever value provided between 50-100, the vehicle is set to 50%, but no error is returned.
I would like to set the vehicle for example to 95%

Does it work for you or is there an issue?

Many thanks in advance for your help

**Comment by mlowijs** [comment]
Hi! You are saying a call like `vehicle.charge.set_charge_limit(95)` does not work as expected?

**Comment by pascal876** [comment]
Hi Michiel,
Yes, if i do vehicle.charge.set_charge_limit(95), the car is set to 50% !
Kind regards,
Pascal
----Message d'origine----
De : notifications@github.com
Date : 20/01/2020 - 09:56 (E)
À : tesla_api@noreply.github.com
Cc : pascal.ethenoz@bluewin.ch, author@noreply.github.com
Objet : Re: [mlowijs/tesla_api] Unable to set vehicle charge limit (#17)
Hi! You are saying a call like vehicle.charge.set_charge_limit(95) does not work as expected?

**Comment by mlowijs** [comment]
Hi! I just ran the following code:

```python
import asyncio
from tesla_api import TeslaApiClient

async def main():
    client = TeslaApiClient("my@email.com", "my@password.com")

    for v in await client.list_vehicles():
        await v.charge.set_charge_limit(80)

asyncio.run(main())
```

This is with Python 3.8 and the tesla_api 2.0.0 package.

**Comment by pascal876** [comment]
Hi Michiel,
Yes, many thanks: it works now!
----Message d'origine----
De : notifications@github.com
Date : 20/01/2020 - 22:15 (E)
À : tesla_api@noreply.github.com
Cc : pascal.ethenoz@bluewin.ch, author@noreply.github.com
Objet : Re: [mlowijs/tesla_api] Unable to set vehicle charge limit (#17)
Hi! I just ran the following code:
 
import asyncio
from tesla_api import TeslaApiClient
asyncdefmain():
    client = TeslaApiClient("my@email.com", "my@password.com")
    for v inawait client.list_vehicles():
        await v.charge.set_charge_limit(80)
asyncio.run(main())
This is with Python 3.8 and the tesla_api 2.0.0 package.
