### ISSUE TITLE
Crypto fails

### ISSUE THREAD

**Issue by PanderMusubi** [mlowijs/tesla_api#2]
Traceback (most recent call last):
      File "./test.py", line 32, in <module>
        print(v.controls.flash_lights())
      File "/usr/local/lib/python3.7/dist-packages/tesla_api/controls.py", line 22, in flash_lights
        return self._api_client.post('vehicles/{}/command/flash_lights'.format(self._vehicle_id))
      File "/usr/local/lib/python3.7/dist-packages/tesla_api/__init__.py", line 85, in post
        raise ApiError(response_json['error'])
    tesla_api.ApiError: Tesla API call failed: verify failed: crypto/rsa: verification error for txid `2xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx0`

**Comment by Dreamsorcerer** [comment]
Closing this, as it's a year old. If this is still reproducible, please reopen (and include any information that might help reproduce).

I've seen this error myself in the past, but I'm not sure I've seen it recently. It also seemed like an intermittent issue on Tesla's side, so I'm not sure there's anything we could fix here (i.e. If I call the same method a second time, it works fine).
